apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test-edge-container

on:
  workflow_dispatch:

jobs:
  container-test:
    runs-on: [self-hosted]
    steps:
      - uses: docker://alpine:latest
        with:
          entrypoint: echo
          args: hello from edge runner container step

      - uses: docker://alpine:latest
        with:
          entrypoint: sh
          args: -c "echo step2 && date"