apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test-edge-container

on:
  workflow_dispatch:

jobs:
  container-test:
    runs-on: [self-hosted]
    steps:
      - uses: docker://alpine:latest
        with:
          entrypoint: echo
          args: hello from entrypoint

      - uses: docker://alpine:latest
        run: echo hello from run command && date